name: ci

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: æ£€å‡ºä»£ç 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: è®¾ç½® Python ç¯å¢ƒ
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Step 3: ç¼“å­˜é…ç½®
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      # Step 4: å®‰è£…ä¾èµ–
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-git-authors-plugin
      - run: pip install mkdocs-git-committers-plugin-2
      - run: pip install mkdocs-rss-plugin
      - run: pip install jieba
      - run: pip install mkdocs-statistics-plugin
      - run: pip install mkdocs-include-dir-to-nav
      - run: pip install mkdocs-markdownextradata-plugin
      - run: pip install mkdocs-material
      - run: pip install --upgrade --force-reinstall mkdocs-material

      # Step 5: æ‰§è¡Œéƒ¨ç½²
      - run: mkdocs gh-deploy --force

      # Step 6: è·å–æäº¤ä¿¡æ¯
      - name: Get Commit Information
        id: commit_info
        run: |
          echo "author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "message=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
          echo "sha=$(git log -1 --pretty=format:'%H')" >> $GITHUB_ENV

      # Step 7: é‚®ä»¶é€šçŸ¥ https://github.com/initchu/action-send-mail
      # - name: Send Email Notification
      #   uses: initchu/action-send-mail@v3
      #   with:
      #     server_address: smtp.163.com      # æ›¿æ¢ä¸ºä½ çš„ SMTP æœåŠ¡å™¨åœ°å€
      #     username: ${{ secrets.SMTP_USERNAME }} # SMTP ç”¨æˆ·åï¼Œå­˜å‚¨åœ¨ GitHub Secrets ä¸­
      #     password: ${{ secrets.SMTP_PASSWORD }} # SMTP å¯†ç ï¼Œå­˜å‚¨åœ¨ GitHub Secrets ä¸­
      #     subject: "ğŸ‰ Deployment Successful - Commit by ${{ env.author }}"
      #     to: 782081987@qq.com #,1304412077@qq.com
      #     from: "è¤šæˆå¿—"            # æ›¿æ¢ä¸ºå‘ä»¶äººé‚®ç®±
      #     body: |
      #       <!DOCTYPE html>
      #       <html>
      #       <head>
      #         <style>
      #           body {
      #             font-family: Arial, sans-serif;
      #             line-height: 1.6;
      #             color: #333333;
      #             margin: 0;
      #             padding: 0;
      #           }
      #           .container {
      #             max-width: 600px;
      #             margin: 20px auto;
      #             padding: 20px;
      #             background-color: #f9f9f9;
      #             border: 1px solid #dddddd;
      #             border-radius: 8px;
      #           }
      #           .header {
      #             text-align: center;
      #             background-color: #0078D4;
      #             color: #ffffff;
      #             padding: 10px 20px;
      #             border-radius: 8px 8px 0 0;
      #           }
      #           .header h1 {
      #             margin: 0;
      #             font-size: 20px;
      #           }
      #           .content {
      #             padding: 20px;
      #           }
      #           .content p {
      #             margin: 10px 0;
      #           }
      #           .content ul {
      #             list-style-type: none;
      #             padding: 0;
      #           }
      #           .content ul li {
      #             margin: 5px 0;
      #             background: #e8f4fc;
      #             padding: 10px;
      #             border-radius: 5px;
      #           }
      #           .content ul li b {
      #             color: #0078D4;
      #           }
      #           .footer {
      #             text-align: center;
      #             margin-top: 20px;
      #             font-size: 12px;
      #             color: #888888;
      #           }
      #           a {
      #             color: #0078D4;
      #             text-decoration: none;
      #           }
      #           a:hover {
      #             text-decoration: underline;
      #           }
      #         </style>
      #       </head>
      #       <body>
      #         <div class="container">
      #           <div class="header">
      #             <h1>ğŸš€ Deployment Notification</h1>
      #           </div>
      #           <div class="content">
      #             <p>Hello,</p>
      #             <p>The deployment of the project has been successfully completed. Here are the details of the latest commit:</p>
      #             <ul>
      #               <li><b>Author:</b> ${{ env.author }}</li>
      #               <li><b>Message:</b> ${{ env.message }}</li>
      #               <li><b>SHA:</b> ${{ env.sha }}</li>
      #             </ul>
      #             <p>You can view the deployment <a href="https://www.chucz.asia">here</a>.</p>
      #           </div>
      #           <div class="footer">
      #             <p>Best regards,<br>è¤šæˆå¿—</p>
      #           </div>
      #         </div>
      #       </body>
      #       </html>

